use_frameworks!

target 'HWModalTransition_Example' do
  pod 'HWModalTransition', :path => '../'

  target 'HWModalTransition_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
